theme: minima
title: Ingesta y análisis de datos de la ENIGH
description: >
  Análisis exploratorio de datos de la Encuesta Nacional de Hogares y Gasto.
author: Julio Waissman Vilanova
email: "julio.waissman@unison.mx"
url: "https://juliowaissman/enhigh-eda"
baseurl: "/" 

minima:
  nav_pages:
    - info_enhigh.md
    - about.md
  skin: dark