theme: minima
title: Documentación de Análisis ENIGH
description: "Análisis exploratorio de datos de la Encuesta Nacional de Hogares y Gasto."
baseurl: "/"
url: "https://juliowaissman/enhigh-eda"
baseurl: "/" 
